language: python
python:
  - "2.7.12"
install:
  - make deps
script:
  - make run
  - sleep 3
  - make test_api
  - make test_ui

deploy:
  provider: heroku
  app: whispering-mountain-24616
  api_key: ${HEROKU_API_KEY}
